### ISSUE TITLE
Changing admin settings doesn't enable save button

### ISSUE THREAD

**Issue by davwheat** [FriendsOfFlarum/reactions#26]
The settings page on the admin panel has a save button, but editing options doesn't enable that button. I can't find a single thing that enables that button!

The weird thing is the settings you change save anyway, leading to a confusing UX.

Can we either use the Save button, or remove it completely, instead using a Google Drive-esque "All changes saved in [Flarum]" message after each change is saved (to prevent more confusion)?

**Comment by datitisev** [comment]
The save button is used for integration with other extensions, I think - like flarum/likes and fof/gamification.

I understand it's confusing if there's no saving indicator. Perhaps simply adding a spinner next to the field that is being saved would do the trick. Or simply just use the Save Settings button.

**Comment by EvilExecutor** [comment]
Looks like this has been answered. Feel free to re-open the issue if you still have problems related to the issue!
