### ISSUE TITLE
setting to "icon" still shows emoji

### ISSUE THREAD

**Issue by widyp** [FriendsOfFlarum/reactions#35]
![Screenshot_20201120-102325](https://user-images.githubusercontent.com/72176874/99754534-246a7500-2b1b-11eb-8ac2-035c60257364.png)
is it just me or?

**Comment by datitisev** [comment]
It shows both. The icon and the emoji if it exists, so if you want to use the emoji instead you can easily view what it looks like. The extension will still respect your selection and use the icon on the forum side.

**Comment by EvilExecutor** [comment]
I will close this issue since it has been addressed. Feel free to re-open if you have problems related to the issue!
