### ISSUE TITLE
FontAwesome icons not working as reactions to avoid CDN use

### ISSUE THREAD

**Issue by poVoq** [FriendsOfFlarum/reactions#45]
## Feature Request
It would be nice to have a simple version with a few standard unicode emojis that does not require loading stuff from a cloudflare CDN, as that is quite a privacy issue.

Thanks for considering.

**Comment by datitisev** [comment]
One currently has the option to use simple FontAwesome icons. I guess we could add an option for plain unicode emojis as well...

**Comment by poVoq** [comment]
Ah I must have missed that option. So with the fontAwesome icons no external CDN is involved?

**Comment by poVoq** [comment]
So switching to "icon" and choosing fontawsome ones doesn't seem to work. I just get an empty box on the reaction icon.

**Comment by datitisev** [comment]
@poVoq I don't think that was broken - what icon names have you tried?

**Comment by poVoq** [comment]
fa-heart for example. The odd thing is that they show up fine in the setting menu and are only broken in the forum itself.

**Comment by datitisev** [comment]
`fa-heart` would be for FA4. I think the admin automatically adds `fa` to icons to show if there's a font awesome alternative - you need to add the full name `fas fa-heart` or whatever.

**Comment by poVoq** [comment]
Hmm this is odd. I can indeed type in `fas fa-heart` in the plugin settings and it will still show up fine there, but it remains a white box in the forum itself (I cleared both flarum cache and ctrl-f5 reloaded the website).

**Comment by datitisev** [comment]
Hm. I'll have to investigate that then...

**Comment by datitisev** [comment]
I never did investigate 😅.

Just checked and it is indeed still an issue. Resolved it in `v1.0.4`.

As for the CDN thing, if that's still wanted that can be a separate issue, as this issue derailed from adding CDN to just using FA icons.
