### ISSUE TITLE
React button title should be translatable

### ISSUE THREAD

**Issue by MarkoKaartinen** [FriendsOfFlarum/reactions#47]
Small thing but I think this title should be translatable also. 

https://github.com/FriendsOfFlarum/reactions/blob/768ccc17e3558b4c83b55f22ac61e0b5b68771bb/js/src/forum/components/PostReactAction.js#L111

**Comment by imorland** [comment]
Good find, patch coming right up :)

**Comment by imorland** [comment]
`1.0.1` released, thanks for raising this issue 👍
