### ISSUE TITLE
Can I get the reactions' information by '/api/discussion/' api ?

### ISSUE THREAD

**Issue by sleptworld** [FriendsOfFlarum/reactions#49]
I want to get the reaction information of the firstPost through '/api/discussions/' api ? I did not find a description. 

Thank you for your answer in advance.

**Comment by datitisev** [comment]
Hello! Sorry, looks like we missed this question. Was it resolved? Do you still need an answer?

**Comment by datitisev** [comment]
I know this is old and never followed up. I added an optional `firstPost.reactions` include to `/api/discussions` & `/api/discussions/:ID`
