### ISSUE TITLE
Update emoji map

### ISSUE THREAD

**Issue by eddiewebb** [FriendsOfFlarum/reactions#50]
## Feature Request

**Is your feature request related to a problem? Please describe.**

This is maybe a bug if you consider "completeness" but otherwise a feature.

I think the emoji map is out of dat and many emojis like [🧑‍🌾](https://emojipedia.org/farmer/#:~:text=The%20Farmer%20emoji%20is%20a,and%20%F0%9F%8C%BE%20Sheaf%20of%20Rice.)  don't work.

**Describe the solution you'd like**

I think your upstream emooji-map just needs to be rebuilt? Or custom shortcodes added for the gaps?

**Describe alternatives you've considered**

**Comment by datitisev** [comment]
I updated my `simple-emoji-map` package for Emoji/Unicode 14 support.... which doesn't matter as Twemoji doesn't have those emotes yet.

_However_, the reason why person farmer doesn't work is because there's some code that ignores combined emojis and just gets the first one... oops!

I've released a fix for that. Update to `v1.0.3` :)

**Comment by eddiewebb** [comment]
I am on 1.0.4 now, and not finding how to make it work.

the 'farmer' emoji to your point is 2 symbols (3 if you include the non-visible joiner character [person, zwj, ear of rice])
https://emojipedia.org/farmer/#:~:text=The%20Farmer%20emoji%20is%20a,and%20%F0%9F%8C%BE%20Sheaf%20of%20Rice.

- 'farmer' does not work
- but neither does 'ear of rice' which is the 2nd character.
- 'person farmer', 'person crop', 'personU+200Dsheaf of rice', 'U+1F9D1 U+200D U+1F33E' etc do not work

https://unicode.org/emoji/charts/full-emoji-list.html#1f9d1_200d_1f33e


I'm at a loss..

**Comment by eddiewebb** [comment]
Twemoji has it, but it's not under a pretty name 

`<img draggable="false" class="emoji" alt="🧑‍🌾" src="https://twemoji.maxcdn.com/v/13.1.0/72x72/1f9d1-200d-1f33e.png">`

![farmer](https://cdn.jsdelivr.net/gh/twitter/twemoji@13/assets/72x72/1f9d1-200d-1f33e.png)

**Comment by eddiewebb** [comment]
pasting `1f9d1-200d-1f33e` works, but I'm not sure that's the UX we want 😆

**Comment by datitisev** [comment]
@eddiewebb `person_farmer` works. Looks like the logic used to search emojis needs improvement as `person farmer` doesn't work... 😅

**Comment by datitisev** [comment]
Think I fixed this with `1.1.0`.
