### ISSUE TITLE
Unable to react since upgrade to 1.3.0

### ISSUE THREAD

**Issue by despecial** [FriendsOfFlarum/reactions#72]
## Bug Report

**Current Behavior**
Unable to add a reaction. Error message: you do not have permission...

**Steps to Reproduce**
Upgrade to 1.3.0 on Flarum 1.8.2

**Expected Behavior**
Add an reaction

**Screenshots**
<img width="760" alt="Bildschirmfoto 2023-10-17 um 20 15 05" src="https://github.com/FriendsOfFlarum/reactions/assets/4135109/d8ee78e9-8562-4d2b-b60d-df6d49b5b482">

![Screenshot 2023-10-17 at 20-15-41 ubertopic](https://github.com/FriendsOfFlarum/reactions/assets/4135109/5aab13a9-be8c-4e1e-9fe3-9a8a18745421)

**Environment**
- Flarum version: 1.8.2
- Extension version: 1.3.2
- Website URL:  not public
- Webserver: [e.g. apache, nginx]
- Hosting environment: shared
- PHP version: 8.1.24
- Browser: Firefox, Safari, Chrome...

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```
Flarum core: 1.8.2
PHP version: 8.1.24
MySQL version: 10.6.15-MariaDB
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, readline, Reflection, SPL, session, standard, restrictdocroot, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, ldap, exif, mysqlnd, PDO, pgsql, Phar, posix, shmop, SimpleXML, soap, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, xmlreader, xmlrpc, zip, amqp, apcu, decimal, gnupg, igbinary, imagick, mailparse, msgpack, yaml, mongodb, redis, Zend OPcache
+--------------------------------------+------------+------------------------------------------+
| Flarum Extensions                    |            |                                          |
+--------------------------------------+------------+------------------------------------------+
| ID                                   | Version    | Commit                                   |
+--------------------------------------+------------+------------------------------------------+
| flarum-flags                         | v1.8.0     |                                          |
| flarum-approval                      | v1.8.0     |                                          |
| flarum-markdown                      | v1.8.0     |                                          |
| flarum-suspend                       | v1.8.1     |                                          |
| flarum-subscriptions                 | v1.8.0     |                                          |
| flarum-tags                          | v1.8.0     |                                          |
| flarum-likes                         | v1.8.0     |                                          |
| therealsujitk-gifs                   | v4.1.1     |                                          |
| matteocontrini-imgur-upload          | v3.9.1     |                                          |
| fof-user-directory                   | 1.3.2      |                                          |
| fof-user-bio                         | 1.3.0      |                                          |
| fof-terms                            | 1.2.1      |                                          |
| fof-subscribed                       | 1.1.3      |                                          |
| fof-stopforumspam                    | 1.2.3      |                                          |
| fof-split                            | 1.1.0      |                                          |
| fof-reactions                        | 1.3.0      |                                          |
| fof-polls                            | 2.1.1      |                                          |
| fof-pages                            | 1.0.7      |                                          |
| fof-nightmode                        | 1.5.3      |                                          |
| fof-merge-discussions                | 1.4.1      |                                          |
| fof-linguist                         | 1.1.1      |                                          |
| fof-ignore-users                     | 1.2.0      |                                          |
| fof-formatting                       | 1.0.3      |                                          |
| fof-follow-tags                      | 1.2.0      | 304a6f79c45d9f5df343e6831cc4f6e3a2bb85a6 |
| fof-doorman                          | 1.1.3      |                                          |
| fof-byobu                            | 1.3.2      |                                          |
| fof-bbcode-details                   | 1.1.1      |                                          |
| flarum-sticky                        | v1.8.0     |                                          |
| flarum-statistics                    | v1.8.0     |                                          |
| flarum-pusher                        | v1.8.0     |                                          |
| flarum-mentions                      | v1.8.2     |                                          |
| flarum-lock                          | v1.8.0     |                                          |
| flarum-lang-german                   | 1.8.2      |                                          |
| flarum-lang-english                  | v1.8.0     |                                          |
| flarum-bbcode                        | v1.8.0     |                                          |
| datlechin-add-like-controls          | v1.0.6     |                                          |
| clarkwinkelmann-selective-mediaembed | 1.0.1      |                                          |
| clarkwinkelmann-post-bookmarks       | 1.0.0      |                                          |
| clarkwinkelmann-likes-received       | 1.0.2      |                                          |
| clarkwinkelmann-collapsible-posts    | 1.0.0      |                                          |
| clarkwinkelmann-author-change        | 1.0.3      |                                          |
| cadiducho-bbcode                     | 1.1        |                                          |
+--------------------------------------+------------+------------------------------------------+

**Comment by deteh** [comment]
Same with 1.3.0, no permission to vote - even for admin. 
Works fine after downgrade to 1.2.0.

Flarum core: 1.8.3
PHP version: 8.2.5

**Comment by imorland** [comment]
I've added a bunch of backend tests, fixed a few minor issues which _may_ have been causing this, although I could not replicate the issue at all locally testing manually.

Please give `1.3.1` a try, and let me know if this solves the issue for you. If it does not, please re-open this issue and share anything relevant from your Flarum log file.

**Comment by imorland** [comment]
Issue remains the same https://discuss.flarum.org/d/20655-friendsofflarum-reactions/238

**Comment by despecial** [comment]
Unfortunately, the latest log we have is from september 29th.
So nothing after upgrading to 1.3.*

**Comment by deteh** [comment]
Did not tried fresh version. 1.3.0 was trhowing:

[2023-10-19 19:19:15] flarum.ERROR: ReflectionException: Class "FoF\Reactions\Middleware\BindRequestToContainer" does not exist in /home/*****/public_html/vendor/illuminate/container/Container.php:877
Stack trace:
#0 /home/*****/public_html/vendor/illuminate/container/Container.php(877): ReflectionClass->__construct()
#1 /home/*****/public_html/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build()
#2 /home/*****/public_html/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#3 /home/*****/public_html/vendor/flarum/core/src/Api/ApiServiceProvider.php(129): Illuminate\Container\Container->make()
#4 /home/*****/public_html/vendor/illuminate/container/Container.php(873): Flarum\Api\ApiServiceProvider->Flarum\Api\{closure}()
#5 /home/*****/public_html/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build()
#6 /home/*****/public_html/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#7 /home/*****/public_html/vendor/illuminate/container/Container.php(1027): Illuminate\Container\Container->make()
#8 /home/*****/public_html/vendor/illuminate/container/Container.php(947): Illuminate\Container\Container->resolveClass()
#9 /home/*****/public_html/vendor/illuminate/container/Container.php(908): Illuminate\Container\Container->resolveDependencies()
#10 /home/*****/public_html/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build()
#11 /home/*****/public_html/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#12 /home/*****/public_html/vendor/flarum/core/src/Frontend/FrontendServiceProvider.php(52): Illuminate\Container\Container->make()
#13 /home/*****/public_html/vendor/flarum/core/src/Forum/ForumServiceProvider.php(130): Flarum\Frontend\FrontendServiceProvider->Flarum\Frontend\{closure}()
#14 /home/*****/public_html/vendor/illuminate/container/Container.php(873): Flarum\Forum\ForumServiceProvider->Flarum\Forum\{closure}()
#15 /home/*****/public_html/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build()
#16 /home/*****/public_html/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#17 /home/*****/public_html/vendor/flarum/core/src/Http/RouteHandlerFactory.php(52): Illuminate\Container\Container->make()
#18 /home/*****/public_html/vendor/illuminate/container/BoundMethod.php(36): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#19 /home/*****/public_html/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /home/*****/public_html/vendor/illuminate/container/BoundMethod.php(81): Illuminate\Container\Util::unwrapIfClosure()
#21 /home/*****/public_html/vendor/illuminate/container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#22 /home/*****/public_html/vendor/illuminate/container/Container.php(653): Illuminate\Container\BoundMethod::call()
#23 /home/*****/public_html/vendor/flarum/core/src/Http/RouteHandlerFactory.php(75): Illuminate\Container\Container->call()
#24 /home/*****/public_html/vendor/flarum/core/src/Http/RouteHandlerFactory.php(37): Flarum\Http\RouteHandlerFactory->resolveController()
#25 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#26 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process()
#27 /home/*****/public_html/vendor/fof/terms/src/Middlewares/RegisterMiddleware.php(59): Laminas\Stratigility\Next->handle()
#28 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\Terms\Middlewares\RegisterMiddleware->process()
#29 /home/*****/public_html/vendor/kilowhat/flarum-ext-audit-pro/src/Middlewares/SetLoggerActor.php(28): Laminas\Stratigility\Next->handle()
#30 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Kilowhat\Audit\Middlewares\SetLoggerActor->process()
#31 /home/*****/public_html/vendor/nearata/flarum-ext-maintenance-mode/src/Middleware/AbstractMiddleware.php(50): Laminas\Stratigility\Next->handle()
#32 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Nearata\MaintenanceMode\Middleware\AbstractMiddleware->process()
#33 /home/*****/public_html/vendor/fof/ban-ips/src/Middleware/RegisterMiddleware.php(94): Laminas\Stratigility\Next->handle()
#34 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\BanIPs\Middleware\RegisterMiddleware->process()
#35 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ContentTypeOptionsHeader.php(21): Laminas\Stratigility\Next->handle()
#36 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ContentTypeOptionsHeader->process()
#37 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ReferrerPolicyHeader.php(30): Laminas\Stratigility\Next->handle()
#38 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ReferrerPolicyHeader->process()
#39 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/FlarumPromotionHeader.php(30): Laminas\Stratigility\Next->handle()
#40 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\FlarumPromotionHeader->process()
#41 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#42 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#43 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle()
#44 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CheckCsrfToken->process()
#45 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle()
#46 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ResolveRoute->process()
#47 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#48 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\SetLocale->process()
#49 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#50 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithSession->process()
#51 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#52 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\RememberFromCookie->process()
#53 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#54 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\StartSession->process()
#55 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#56 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CollectGarbage->process()
#57 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#58 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ParseJsonBody->process()
#59 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#60 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\HandleErrors->process()
#61 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#62 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\InjectActorReference->process()
#63 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#64 /home/*****/public_html/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#65 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\RequestHandler->process()
#66 /home/*****/public_html/vendor/middlewares/base-path-router/src/BasePathRouter.php(99): Laminas\Stratigility\Next->handle()
#67 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePathRouter->process()
#68 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#69 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\OriginalMessages->process()
#70 /home/*****/public_html/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#71 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePath->process()
#72 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#73 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ProcessIp->process()
#74 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#75 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process()
#76 /home/*****/public_html/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(73): Laminas\Stratigility\MiddlewarePipe->handle()
#77 /home/*****/public_html/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#78 /home/*****/public_html/public/index.php(32): Flarum\Http\Server->listen()
#79 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [FoF\Reactions\Middleware\BindRequestToContainer] does not exist. in /home/*****/public_html/vendor/illuminate/container/Container.php:879
Stack trace:
#0 /home/*****/public_html/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build()
#1 /home/*****/public_html/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#2 /home/*****/public_html/vendor/flarum/core/src/Api/ApiServiceProvider.php(129): Illuminate\Container\Container->make()
#3 /home/*****/public_html/vendor/illuminate/container/Container.php(873): Flarum\Api\ApiServiceProvider->Flarum\Api\{closure}()
#4 /home/*****/public_html/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build()
#5 /home/*****/public_html/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#6 /home/*****/public_html/vendor/illuminate/container/Container.php(1027): Illuminate\Container\Container->make()
#7 /home/*****/public_html/vendor/illuminate/container/Container.php(947): Illuminate\Container\Container->resolveClass()
#8 /home/*****/public_html/vendor/illuminate/container/Container.php(908): Illuminate\Container\Container->resolveDependencies()
#9 /home/*****/public_html/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build()
#10 /home/*****/public_html/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#11 /home/*****/public_html/vendor/flarum/core/src/Frontend/FrontendServiceProvider.php(52): Illuminate\Container\Container->make()
#12 /home/*****/public_html/vendor/flarum/core/src/Forum/ForumServiceProvider.php(130): Flarum\Frontend\FrontendServiceProvider->Flarum\Frontend\{closure}()
#13 /home/*****/public_html/vendor/illuminate/container/Container.php(873): Flarum\Forum\ForumServiceProvider->Flarum\Forum\{closure}()
#14 /home/*****/public_html/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build()
#15 /home/*****/public_html/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#16 /home/*****/public_html/vendor/flarum/core/src/Http/RouteHandlerFactory.php(52): Illuminate\Container\Container->make()
#17 /home/*****/public_html/vendor/illuminate/container/BoundMethod.php(36): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#18 /home/*****/public_html/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#19 /home/*****/public_html/vendor/illuminate/container/BoundMethod.php(81): Illuminate\Container\Util::unwrapIfClosure()
#20 /home/*****/public_html/vendor/illuminate/container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#21 /home/*****/public_html/vendor/illuminate/container/Container.php(653): Illuminate\Container\BoundMethod::call()
#22 /home/*****/public_html/vendor/flarum/core/src/Http/RouteHandlerFactory.php(75): Illuminate\Container\Container->call()
#23 /home/*****/public_html/vendor/flarum/core/src/Http/RouteHandlerFactory.php(37): Flarum\Http\RouteHandlerFactory->resolveController()
#24 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#25 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process()
#26 /home/*****/public_html/vendor/fof/terms/src/Middlewares/RegisterMiddleware.php(59): Laminas\Stratigility\Next->handle()
#27 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\Terms\Middlewares\RegisterMiddleware->process()
#28 /home/*****/public_html/vendor/kilowhat/flarum-ext-audit-pro/src/Middlewares/SetLoggerActor.php(28): Laminas\Stratigility\Next->handle()
#29 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Kilowhat\Audit\Middlewares\SetLoggerActor->process()
#30 /home/*****/public_html/vendor/nearata/flarum-ext-maintenance-mode/src/Middleware/AbstractMiddleware.php(50): Laminas\Stratigility\Next->handle()
#31 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Nearata\MaintenanceMode\Middleware\AbstractMiddleware->process()
#32 /home/*****/public_html/vendor/fof/ban-ips/src/Middleware/RegisterMiddleware.php(94): Laminas\Stratigility\Next->handle()
#33 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\BanIPs\Middleware\RegisterMiddleware->process()
#34 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ContentTypeOptionsHeader.php(21): Laminas\Stratigility\Next->handle()
#35 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ContentTypeOptionsHeader->process()
#36 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ReferrerPolicyHeader.php(30): Laminas\Stratigility\Next->handle()
#37 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ReferrerPolicyHeader->process()
#38 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/FlarumPromotionHeader.php(30): Laminas\Stratigility\Next->handle()
#39 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\FlarumPromotionHeader->process()
#40 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#41 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#42 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle()
#43 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CheckCsrfToken->process()
#44 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle()
#45 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ResolveRoute->process()
#46 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#47 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\SetLocale->process()
#48 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#49 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithSession->process()
#50 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#51 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\RememberFromCookie->process()
#52 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#53 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\StartSession->process()
#54 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#55 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CollectGarbage->process()
#56 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#57 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ParseJsonBody->process()
#58 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#59 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\HandleErrors->process()
#60 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#61 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\InjectActorReference->process()
#62 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#63 /home/*****/public_html/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#64 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\RequestHandler->process()
#65 /home/*****/public_html/vendor/middlewares/base-path-router/src/BasePathRouter.php(99): Laminas\Stratigility\Next->handle()
#66 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePathRouter->process()
#67 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#68 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\OriginalMessages->process()
#69 /home/*****/public_html/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#70 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePath->process()
#71 /home/*****/public_html/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#72 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ProcessIp->process()
#73 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#74 /home/*****/public_html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process()
#75 /home/*****/public_html/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(73): Laminas\Stratigility\MiddlewarePipe->handle()
#76 /home/*****/public_html/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#77 /home/*****/public_html/public/index.php(32): Flarum\Http\Server->listen()
#78 {main} 

Before you ask, migrations were run, flarum cache cleared and i assume after package upgrade new autoload was generated by composer.

**Comment by NathanSweet** [comment]
Same problem here, 1.3.1. I see a number of these in the log, maybe unrelated (`flarum-tags` is 1.8.0):
```
[2023-10-22 18:16:23] flarum.ERROR: TypeError: Unsupported operand types: string - int in /path/to/flarum/vendor/flarum/tags/src/Content/Tag.php:84
Stack trace:
#0 /path/to/flarum/vendor/flarum/core/src/Frontend/Frontend.php(62): Flarum\Tags\Content\Tag->__invoke()
#1 /path/to/flarum/vendor/flarum/core/src/Frontend/Frontend.php(54): Flarum\Frontend\Frontend->populate()
#2 /path/to/flarum/vendor/flarum/core/src/Frontend/Controller.php(32): Flarum\Frontend\Frontend->document()
...
```

**Comment by imorland** [comment]
Thanks to @NathanSweet letting me poke around on his server, I've now found the cause of the issue here. I'm working on a patch now and hope to release a fix very shortly
