### ISSUE TITLE
Reacts are not showing anymore

### ISSUE THREAD

**Issue by Profi420** [FriendsOfFlarum/reactions#76]
The reactions are not working anymore. At least, it only shows part of it.

**Comment by imorland** [comment]
I also had this problem, but it turns out my PiHole had started blocking the domain, seems `cdn/jsdelivr.net` was added to Gravity recently...

**Comment by Profi420** [comment]
Hi!
I don't use PiHole. So what should I do to fix this issue? We are hosted by FreeFlarum which uses the newest version

**Comment by yk2k2** [comment]
We have exactly the same problem. I think it was due to the last update. Is the error already known? In the discuss.Flarum ga there is no answer to this yet

**Comment by yk2k2** [comment]
https://discuss.flarum.org/d/20655-friendsofflarum-reactions/250

**Comment by yk2k2** [comment]
> I also had this problem, but it turns out my PiHole had started blocking the domain, seems `cdn/jsdelivr.net` was added to Gravity recently...

Should we use custom CDN? which one?
